/* tslint:disable */
/* eslint-disable */
/**
 * WarEra API
 * WarEra tRPC API endpoints. ⚠️ Please notice that every call is in GET and not POST.
 *
 * The version of the OpenAPI document: 0.17.4-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

